"""Shared source modules."""

from packages.shared.src.circuit_breaker import (
    CircuitBreaker,
    CircuitBreakerConfig,
    CircuitBreakerError,
    CircuitBreakerRegistry,
    CircuitState,
    CircuitStats,
    ResilientCall,
    RetryConfig,
    RetryWithBackoff,
    circuit_breaker,
    get_circuit_breaker,
    resilient,
    retry_with_backoff,
)
from packages.shared.src.config import Settings, get_settings, reload_settings
from packages.shared.src.exceptions import (
    AIProviderError,
    AITimeoutError,
    AllProvidersFailedError,
    AuthenticationError,
    ConfigurationError,
    ConnectionError,
    DailyLossExceededError,
    ErrorCode,
    InsufficientBalanceError,
    InvalidOrderError,
    MaxPositionsReachedError,
    MissingCredentialsError,
    OrderRejectedError,
    PaperModeViolationError,
    PositionNotFoundError,
    RateLimitError,
    RiskLimitExceededError,
    SymbolNotFoundError,
    TimeoutError,
    TradingPlatformError,
)
from packages.shared.src.logging import (
    ai_logger,
    get_logger,
    setup_logging,
    trading_logger,
)
from packages.shared.src.models import (
    OHLCV,
    ExchangeInfo,
    MarketRegime,
    Order,
    OrderStatus,
    OrderType,
    PerformanceMetrics,
    Platform,
    Position,
    Side,
    Signal,
    SignalAction,
    Trade,
    deserialize,
    serialize,
)
from packages.shared.src.utils import (
    RateLimiter,
    calculate_pnl,
    calculate_position_size,
    chunk_list,
    clamp,
    format_currency,
    format_percentage,
    generate_id,
    generate_idempotency_key,
    round_decimal,
    safe_divide,
    timestamp_ms,
    utc_now,
)

__all__ = [
    "OHLCV",
    "AIProviderError",
    "AITimeoutError",
    "AllProvidersFailedError",
    "AuthenticationError",
    # Circuit Breaker
    "CircuitBreaker",
    "CircuitBreakerConfig",
    "CircuitBreakerError",
    "CircuitBreakerRegistry",
    "CircuitState",
    "CircuitStats",
    "ConfigurationError",
    "ConnectionError",
    "DailyLossExceededError",
    # Exceptions
    "ErrorCode",
    "ExchangeInfo",
    "InsufficientBalanceError",
    "InvalidOrderError",
    "MarketRegime",
    "MaxPositionsReachedError",
    "MissingCredentialsError",
    "Order",
    "OrderRejectedError",
    "OrderStatus",
    "OrderType",
    "PaperModeViolationError",
    "PerformanceMetrics",
    # Models
    "Platform",
    "Position",
    "PositionNotFoundError",
    "RateLimitError",
    "RateLimiter",
    "ResilientCall",
    "RetryConfig",
    "RetryWithBackoff",
    "RiskLimitExceededError",
    # Config
    "Settings",
    "Side",
    "Signal",
    "SignalAction",
    "SymbolNotFoundError",
    "TimeoutError",
    "Trade",
    "TradingPlatformError",
    "ai_logger",
    "calculate_pnl",
    "calculate_position_size",
    "chunk_list",
    "circuit_breaker",
    "clamp",
    "deserialize",
    "format_currency",
    "format_percentage",
    # Utils
    "generate_id",
    "generate_idempotency_key",
    "get_circuit_breaker",
    "get_logger",
    "get_settings",
    "reload_settings",
    "resilient",
    "retry_with_backoff",
    "round_decimal",
    "safe_divide",
    "serialize",
    # Logging
    "setup_logging",
    "timestamp_ms",
    "trading_logger",
    "utc_now",
]
